### ISSUE TITLE
Raise an Error if 0-length section is found at the soma

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/NeuroR#106]
This is related to #105.

## Context

Currently, if a 0-length section is found at the soma, `sanitize` will drop the entire neurite that is attached to it.

This behavior is not what a normal user could expect, especially because there is no Warning or Error when this dropping takes place during sanitization and the user cannot know that this has happened.

## Action

After discussions (@lidakanari @adrien-berchet @mgeplf @eleftherioszisis) we agreed that the solution would be to raise an informative Error (e.g. `ValueError("Zero-length section found at the soma ..."`)  and terminate the execution of `sanitize`.

**Comment by eleftherioszisis** [comment]
The proposal has been implemented in #107.
