### ISSUE TITLE
Incorrect type hint for axons

### ISSUE THREAD

**Issue by asanin-epfl** [BlueBrain/NeuroR#34]
In https://github.com/BlueBrain/NeuroR/blob/master/neuror/main.py#L243

Should be something like `axons: Optional[List] = None,` instead of `axons: Optional[Path] = None,`.

**Comment by mgeplf** [comment]
Would mypy have caught this?

**Comment by asanin-epfl** [comment]
yep, for sure

**Comment by wizmer** [comment]
Fixed in #48
