### ISSUE TITLE
Segfault in fix_zero_diameters because of stack limit

### ISSUE THREAD

**Issue by adrien-berchet** [BlueBrain/NeuroR#78]
When using `neuror.zero_diameter_fixer.fix_zero_diameters` on the attached morphology, I get a segmentation fault.
After some investigation with @arnaudon , it appeared that it happens when the Python recursion limit is updated in the function with `sys.setrecursionlimit` and is set to a value greater than the actual stack size (which can be updated using `ulimit -s <new_size>`). When increasing the stack size with `ulimit` the problem disappears.

Here is a MWE:
First update the stack size in bash then run Python:
```bash
    ulimit -s 8192
    python
```
Then in Python:
```python
    import morphio
    from neuror.zero_diameter_fixer import fix_zero_diameters
    morph = morphio.mut.Morphology("AA0319.asc")
    fix_zero_diameters(morph)
```
It should end in a segfault while the same with `ulimit -s 16384` should pass.

I think the best way to solve this issue would be to change the algorithm to avoid recursion. But it might not be easy...

[AA0319.asc.zip](https://github.com/BlueBrain/NeuroR/files/6323621/AA0319.asc.zip)

**Comment by mgeplf** [comment]
Hitting `sys.setrecursionlimit` usually points to an algorithmic problem (ie: infinite recursion), so I would expect that changing it doesn't fix it.

Having https://github.com/BlueBrain/NeuroR/blob/master/neuror/zero_diameter_fixer.py#L186 in the code is very suspicious.

It appears `fix_from_downstream`, and `fix_from_downstream` all recurse; they should prob. be changed to a list based approach like (on cursory inspection) `fix_in_between` does.

**Comment by adrien-berchet** [comment]
> Hitting `sys.setrecursionlimit` usually points to an algorithmic problem (ie: infinite recursion), so I would expect that changing it doesn't fix it.
I fully agree with this.

**Comment by arnaudon** [comment]
We can put this in our todo list. Also, we need to see how it was originally coded in cpp. Is this also a code benoit transcribed from RepairSDK?

**Comment by mgeplf** [comment]
> EDIT: the recursion is not infinite, it just depends on the size of the morphology,

Yeah, I agree: that's why I linked the suspicious code: it appears to have been a known issue, but the work around is fragile.

> Also, we need to see how it was originally coded in cpp. Is this also a code benoit transcribed from RepairSDK?

There are comments in the docstrings on where it came from (MUK).

**Comment by arnaudon** [comment]
Great! Do you think this is an issue you can resolve, or we need to allocate some time to it? it is not so urgent, as the stack size on bb5 is huge.

**Comment by mgeplf** [comment]
@asanin-epfl is looking into it.
